apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set-pessoa-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-pessoa-app
  template:
    metadata:
      labels:
        app: pod-pessoa-app
    spec:
      containers:
        - name: pod-pessoa-app
          image: gtbarbosa/k8s-app-java-mysql
          ports:
            - containerPort: 8080